config/routes.rb
Welovemerthyr::Application.routes.draw do
  #match 'auth/:provider/callback' => 'subscribers#callback_facebook'
  #match 'auth/failure' => redirect('/')
  post 'auth/:provider/callback' => 'subscribers#callback_facebook'
  post 'auth/failure' => redirect('/')

  scope "public" do
    # New Subscriber
    get '/new_subscriber' => 'pages#new_subscriber', as: 'public_new_subscriber'
    post '/create_subscriber' => 'pages#create_subscriber'
    
    get '/privacy_policy' => 'pages#privacy_policy', as: 'public_privacy_policy'
    # Homepage.
    get '/front' => 'pages#front'

    # Blog index/post pages.
    get '/blog' => 'pages#blog'
    get '/blog_post/:id' => 'pages#blog_post', as: 'blog_post'

    # Events index/show pages.
    get '/events' => 'pages#events', as: 'public_events'
    get '/event/:id' => 'pages#event', as: 'public_event'

    # Vouchers index/show page.
    get '/vouchers' => 'pages#vouchers', as: 'public_vouchers'
    get '/vouchers/:id' => 'pages#voucher', as: 'public_voucher'

    # Businesses page and business page.
    get '/businesses_category/:cat' => 'pages#businesses_category', as: 'public_businesses_category'
    get '/businesses/search' => 'pages#businesses_results', as: 'public_businesses_search'
    get '/businesses/:id' => 'pages#business', as: 'public_business'

    # Static pages edit by admin.
    get '/templates/:id' => 'pages#static_page', as: 'public_static_page'

    get '/visiting' => 'pages#visiting', as: 'public_visiting'
    get '/guides' => 'pages#guides', as: 'public_guides'

    get '/update_guides_map' => 'pages#update_guides_map', as: 'update_guides_map'

    get 'pages/:id' => 'pages#public_show', as: 'public_page_show'
  end

  scope "admin" do
    resources :pages do
      get 'admin', on: :collection
    end

    resources :businesses do
      post '/invite' => 'businesses#invite', on: :member
      get '/less_active' => 'businesses#less_active', on: :collection, as: :less_active
    end

    resources :deals, path: 'vouchers'
    resources :page_templates
    resources :posts
    resources :sliders
    resources :events
    resources :business_category_templates
    resources :downloads
    resources :subscribers do
      post '/subsribe' => 'subscribers#subscribe', on: :collection
    end
    
  end

  resources :subscribers do
    post '/subsribe' => 'subscribers#subscribe', on: :collection
  end

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

  get '/admin' => redirect('/admin/pages/admin'), as: 'admin'

  root to: 'pages#front'

  api vendor_string: "welovemerthyr", default_version: 1 do
    version 1 do
      cache as: 'v1' do
        match :posts, to: 'posts#index', via: [:options]
        resources :posts, only:  %w(index show)

        match :events, to: 'events#index', via: [:options]
        match 'events/:id', to: 'events#show', via: [:options]
        resources :events, only:  %w(index show)

        match :deals, to: 'deals#index', via: [:options]
        match 'deals/:id', to: 'deals#show', via: [:options]
        resources :deals, only:  %w(index show)

        match :businesses, to: 'businesses#index', via: [:options]
        match 'businesses/:id', to: 'businesses#show', via: [:options]
        resources :businesses, only:  %w(index show)

        match :business_categories, to: 'businesses#index', via: [:options]
        get 'business_categories', to: "businesses#index" 

        match 'business_categories/:category', to: 'businesses#index', via: [:options]
        get 'business_categories/:category', to: "businesses#index" 

        match 'deleted_records', to: 'deleted_records#index', via: [:options]
        resources :deleted_records, only:  %w(index)
      end
    end

  end

  #redirects
  get '/facebook' => redirect('http://www.facebook.com/welovemerthyr')
  get '/twitter' => redirect('http://www.twitter.com/welovemerthyr')
  get '/xmas2014_fb' => redirect('https://www.facebook.com/events/1468240193457417')
end

app/views/shared/_business_update_script.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyAS2tiGZYnoio9bzZ-BuRivI2R6ib9G0Jw&amp;sensor=true&amp;libraries=geometry" type="text/javascript"></script>
<div class="panel">
  <div class="panel-content">
    <div class='padding_top_20'>
      <div>
        <div id="map" style="height:500px;width:67%"></div>

        <script type="text/javascript">
          $(document).ready(function() {
            var geocoder;
            var map;
            var marker;
            geocoder = new google.maps.Geocoder();
            var latlng = new google.maps.LatLng(-34.397, 150.644);
            var mapOptions = {
              zoom: 8,
              center: latlng,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            map = new google.maps.Map(document.getElementById('map'), mapOptions);
            google.maps.event.addListener(map, 'click', function() {
            });
            var infowindow = new google.maps.InfoWindow({size: new google.maps.Size(150,50)});
            
            codeAddress();
            
            function geocodePosition(pos) {
              geocoder.geocode({
                latLng: pos
              }, function(responses) {
                var address = ""
                if (responses && responses.length > 0) {
                  marker.formatted_address = responses[0].formatted_address;
                  for (var i = 0; i < responses[0].address_components.length; i++) {
                    var addr = responses[0].address_components[i];
                    if (addr.types[0] == 'street_address')
                      marker.address = address + addr.long_name;
                    else if (addr.types[0] == 'route')
                      marker.address = address + addr.long_name;
                    else if (addr.types[0] == ['administrative_area_level_2'])
                      marker.town = addr.long_name;
                    else if (addr.types[0] == ['postal_code'])
                      marker.postal_code = addr.long_name;
               }

                set_elements();
                
                } else {
                  marker.formatted_address = 'Cannot determine address at this location.';
                }
                infowindow.setContent(marker.formatted_address+"<br>coordinates: "+marker.getPosition().toUrlValue(6));
                infowindow.open(map, marker);
              });
            }

            function set_elements(){
              document.getElementById('business_address').value = marker.address
              document.getElementById('business_town').value = marker.town
              document.getElementById('business_postcode').value = marker.postal_code

            }

            function codeAddress() {
              var address = document.getElementById('business_address').value
              var lat = document.getElementById('business_lat').value
              var lng = document.getElementById('business_lon').value
              var latlng = {lat: parseFloat(lat), lng: parseFloat(lng)};
              geocoder.geocode( { 'location': latlng}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                  map.setCenter(results[0].geometry.location);
                  if (marker) {
                     marker.setMap(null);
                     if (infowindow) infowindow.close();
                  }
                  marker = new google.maps.Marker({
                      map: map,
                      draggable: true,
                      position: results[0].geometry.location
                  });
                  google.maps.event.addListener(marker, 'dragend', function() {
                    // updateMarkerStatus('Drag ended');
                    geocodePosition(marker.getPosition());
                  });
                  google.maps.event.addListener(marker, 'click', function() {
                    if (marker.formatted_address) {
                      infowindow.setContent(marker.formatted_address+"<br>coordinates: "+lat+" "+lng);
                    } else  {
                      infowindow.setContent(address+"<br>coordinates: "+lat+" "+lng);
                    }
                    infowindow.open(map, marker);
                  });
                  google.maps.event.trigger(marker, 'click');
                } else {
                  alert('Geocode was not successful for the following reason: ' + status);
                }
              });
            }

          })
        </script>
        <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"> 
              </script> 
              <script type="text/javascript"> 
              _uacct = "UA-162157-1";
              urchinTracker();
              </script>
      </div>
    </div>
  </div>
</div>

app/views/shared/_gmap_script.html.erb
handler = Gmaps.build('Google', { markers: { maxRandomDistance: null }});
handler.buildMap({ provider: { scrollwheel: false }, internal: {id: 'map'} }, function(){
  markers = handler.addMarkers(<%=raw hash.to_json -%>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  <%- if defined? zoom_level -%>
    handler.getMap().setZoom(<%= zoom_level -%>);
  <%- end -%>
  if (markers.length == 1) {
    handler.getMap().setZoom(17);
  }
});

app/views/shared/_latest_vouchers.html.erb
<!-- replaced by the subscribe image -->

<!--

<div class="panel equalHeights">
  <div class=" palette palette-success" >Latest Vouchers</div>
  <div class="list-group latest_vouchers">
    <%#- Deal.latest(3).each do |d| -%>
      <%#= link_to public_voucher_path(d), class: 'list-group-item' do -%>
        <span class="glyphicon glyphicon-pound"></span>
        <div class="col-md-10">
          <span class="title"><%#= d.title -%></span>
          <span class="desc">at <%#= d.business_name -%></span>
        </div>
      <%#- end -%>
    <%#- end -%>
  </div>
</div>

<%#= link_to 'More vouchers', public_vouchers_path, class: 'btn btn-s btn-success pull-right' -%>

<div class="clearfix"></div>

-->

app/views/shared/_sidebar_calendar.html.erb
<div class="events_calendar">
  <h2 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
  </h2>
  <%= calendar @date do |date| %>
      <p class="calendar_day" data-toggle="popover">
        <%= date.day %>
      </p>
      <!--< %- if @events_by_date[date] %>-->
          <ul>
            <% @events.each do |event| %>
                <!--< % events[1].each do |event| %>-->
                    <%- if event.next_occurrence.to_date == date %>
                        <li><%= link_to event.name, public_event_path(event) %></li>
                    <% end %>
                <!--< % end %>-->
            <% end %>
          </ul>
      <!--< % end %>-->
  <% end %>
</div>

app/views/shared/_sidebar_download_links-bk.html.erb
<%- downloads = Download.desc(:created_at).desc(:id) -%>

<div class="panel equalHeights">
  <div class="palette palette-success">Downloads</div>

  <!--div class="row" style="margin-left:0; margin-right:0; margin-bottom:20px">
    <div class="col-lg-12 download-toggle-wrap">
      <a href="#" class="download-toggle-btn" id="events">Events &amp; Marketing</a>
    </div>
    <div class="col-lg-12 download-toggle-wrap">
      <a href="#" class="download-toggle-btn" id="reports">Reports</a>
    </div>
    <div class="col-lg-12 download-toggle-wrap">
      <a href="#" class="download-toggle-btn" id="newsletters">Newsletters</a>
    </div>
    <div class="col-lg-12 download-toggle-wrap">
      <a href="#" class="download-toggle-btn" id="general">General</a>
    </div>
    <h5 class="red text-center" style="line-height:1.4; text-transform: none">Toggle The Categories With The Buttons Above</h5>
  </div-->


<div class="dropdown download-dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Category
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><a href="#" class="events">Events &amp; Marketing</a></li>
      <li><a href="#" class="reports">Reports</a></li>
      <li><a href="#" class="newsletters">Newsletters</a></li>
      <li><a href="#" class="general">General</a></li>
    </ul>
  </div>


  <div id="downloadlist">
    <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
    <div class="viewport">
        <div class="overview">
          <div class="list-group download_links">
            <%- if downloads.any? -%>
              <%- downloads.each do |d| -%>
                <a href="<%= d.file.url -%>" class="list-group-item <%= !d.category.blank? ? d.category.downcase.tr(" ", '_') : nil -%>">
                <div class="col-md-10">
                  <span class="title"><%= d.title -%></span>
                </div>
              <%- end -%>
            <%- else -%>
              <%= link_to '#', class: 'list-group-item' do -%>
                <div class="col-md-10">
                  <span class="title"> No files. </span>
                </div>
              <%- end -%>
            <%- end -%>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar_download_links.html.erb
<%- downloads = Download.desc(:created_at).desc(:id) -%>

<button id="select-category-btn" class="button expanded" type="button" data-toggle="download-dropdown">Select Category</button>
<div class="dropdown-pane" data-position="right" data-alignment="bottom" id="download-dropdown" data-dropdown data-auto-focus="true">
  <ul class="menu vertical">
    <li><a href="#" class="events"><i class="fa fa-calendar"></i><span>Events &amp; Marketing</span></a></li>
    <li><a href="#" class="reports"><i class="fa fa-file-o"></i><span>Reports</span></a></li>
    <li><a href="#" class="newsletters"><i class="fa fa-newspaper-o"></i><span>Newsletters</span></a></li>
    <li><a href="#" class="general"><i class="fa fa-bell-o"></i><span>General</span></a></li>
  </ul>
</div>

<div id="downloadlist">
  <div class="list-group download_links">
    <%- if downloads.any? -%>
      <%- downloads.each do |d| -%>
        <a href="<%= d.file.url -%>" class="list-group-item <%= !d.category.blank? ? d.category.downcase.tr(" ", '_') : nil -%>">
          <span class="title"><%= d.title -%></span>
        </a>
      <%- end -%>
    <%- else -%>
      <%= link_to '#', class: 'list-group-item' do -%>
          <span class="title"> No files. </span>
      <%- end -%>
    <%- end -%>
  </div>
</div>

app/views/shared/_sidebar_search.html.erb
<h2 class="red">What are you looking for?</h2>

<p>If there's something specific that you're looking for one of our shops has probably got it.</p>
<p>Search below:</p>

<div class="input-group ">
  <%= form_tag public_businesses_search_path, method: 'get', id: 'sidebar-search' do -%>
    <input type="text" class="form-control" placeholder="eg. Shoes" name='query'>

    <span class="input-group-btn">
      <button class="btn btn-default" type="submit"><span class="icon-search"></span></button>
    </span>
  <%- end -%>
</div>

app/views/shared/_sidebar_socials.html.erb
<!--
<h4 class="red margin_bottom_20">Follow us and find out what's going on in Merthyr Tydfil Town Centre</h4>
<a class="btn btn-s btn-red " href=""> <span class="glyphicon icon-pinterest"></span>Pin It<span class="badge no_bg">100</span></a>
<div class="clearfix"></div>
<a class="btn btn-s btn-blue " href=""><span class="glyphicon icon-linkedin"></span>Share<span class="badge no_bg">91</span></a>
<div class="clearfix"></div>
<a class="btn btn-s btn-danger " href=""><span class="glyphicon icon-stumble"></span>Stumble<span class="badge no_bg">45</span></a>
<div class="clearfix"></div>
<a class="btn btn-s btn-black " href=""><span class="glyphicon icon-google-plus"></span>Connect with Google</a>
<div class="clearfix"></div>
<a class="btn btn-s btn-dark_blue " href=""><span class="glyphicon icon-facebook-sign"></span>Connect with Facebook</a>
<div class="clearfix"></div>
<a class="btn btn-s btn-twitter " href=""><span class="glyphicon icon-twitter"></span>Connect with Twitter</a>
<div class="clearfix"></div>
-->

<div class="fb-like-box" data-href="http://www.facebook.com/welovemerthyr" data-width="360" data-height="The pixel height of the plugin" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="true" data-show-border="true"></div>

app/views/shared/_sidebar_tags.html.erb
<h2>Some things you can find:</h2>

<div class="white_block widget_tag">
  <%- if defined? tags -%>
    <%- tags.each do |t| -%>
      <a class="btn btn-xs btn-primary " href="<%= public_businesses_category_path(t[:business].category, tag: t[:tag].strip) -%>"><%= t[:tag] -%></a>
    <%- end -%>
  <%- end -%>
</div>