config/routes.rb
Welovemerthyr::Application.routes.draw do
  #match 'auth/:provider/callback' => 'subscribers#callback_facebook'
  #match 'auth/failure' => redirect('/')
  post 'auth/:provider/callback' => 'subscribers#callback_facebook'
  post 'auth/failure' => redirect('/')

  scope "public" do
    # New Subscriber
    get '/new_subscriber' => 'pages#new_subscriber', as: 'public_new_subscriber'
    post '/create_subscriber' => 'pages#create_subscriber'
    
    get '/privacy_policy' => 'pages#privacy_policy', as: 'public_privacy_policy'
    # Homepage.
    get '/front' => 'pages#front'

    # Blog index/post pages.
    get '/blog' => 'pages#blog'
    get '/blog_post/:id' => 'pages#blog_post', as: 'blog_post'

    # Events index/show pages.
    get '/events' => 'pages#events', as: 'public_events'
    get '/event/:id' => 'pages#event', as: 'public_event'

    # Vouchers index/show page.
    get '/vouchers' => 'pages#vouchers', as: 'public_vouchers'
    get '/vouchers/:id' => 'pages#voucher', as: 'public_voucher'

    # Businesses page and business page.
    get '/businesses_category/:cat' => 'pages#businesses_category', as: 'public_businesses_category'
    get '/businesses/search' => 'pages#businesses_results', as: 'public_businesses_search'
    get '/businesses/:id' => 'pages#business', as: 'public_business'

    # Static pages edit by admin.
    get '/templates/:id' => 'pages#static_page', as: 'public_static_page'

    get '/visiting' => 'pages#visiting', as: 'public_visiting'
    get '/guides' => 'pages#guides', as: 'public_guides'

    get '/update_guides_map' => 'pages#update_guides_map', as: 'update_guides_map'

    get 'pages/:id' => 'pages#public_show', as: 'public_page_show'
  end

  scope "admin" do
    resources :pages do
      get 'admin', on: :collection
    end

    resources :businesses do
      post '/invite' => 'businesses#invite', on: :member
      get '/less_active' => 'businesses#less_active', on: :collection, as: :less_active
    end

    resources :deals, path: 'vouchers'
    resources :page_templates
    resources :posts
    resources :sliders
    resources :events
    resources :business_category_templates
    resources :downloads
    resources :subscribers do
      post '/subsribe' => 'subscribers#subscribe', on: :collection
    end
    
  end

  resources :subscribers do
    post '/subsribe' => 'subscribers#subscribe', on: :collection
  end

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

  get '/admin' => redirect('/admin/pages/admin'), as: 'admin'

  root to: 'pages#front'

  api vendor_string: "welovemerthyr", default_version: 1 do
    version 1 do
      cache as: 'v1' do
        match :posts, to: 'posts#index', via: [:options]
        resources :posts, only:  %w(index show)

        match :events, to: 'events#index', via: [:options]
        match 'events/:id', to: 'events#show', via: [:options]
        resources :events, only:  %w(index show)

        match :deals, to: 'deals#index', via: [:options]
        match 'deals/:id', to: 'deals#show', via: [:options]
        resources :deals, only:  %w(index show)

        match :businesses, to: 'businesses#index', via: [:options]
        match 'businesses/:id', to: 'businesses#show', via: [:options]
        resources :businesses, only:  %w(index show)

        match :business_categories, to: 'businesses#index', via: [:options]
        get 'business_categories', to: "businesses#index" 

        match 'business_categories/:category', to: 'businesses#index', via: [:options]
        get 'business_categories/:category', to: "businesses#index" 

        match 'deleted_records', to: 'deleted_records#index', via: [:options]
        resources :deleted_records, only:  %w(index)
      end
    end

  end

  #redirects
  get '/facebook' => redirect('http://www.facebook.com/welovemerthyr')
  get '/twitter' => redirect('http://www.twitter.com/welovemerthyr')
  get '/xmas2014_fb' => redirect('https://www.facebook.com/events/1468240193457417')
end

app/controllers/api/v1/businesses_controller.rb
class Api::V1::BusinessesController < Api::BaseController
  PER_PAGE = 25

  ##
  # Returns paginated collection of businesses
  #
  # GET /api/v1/businesses
  #
  #. Also can filter by category.
  #
  # GET /api/v1/businesses/Shopping
  #
  # To filter by service tag, pass tag name as a query param.
  #
  # GET /api/v1/businesses/?tag=cloths
  # GET /api/v1/businesses/Shopping/?tag=cloths
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/businesses
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   [{"id":"522e2ea69ef1ea5cdf000008","name":"4 Sure Wales","category":"Services","address":"7 Glebeland Street ",
  #   "town":"Merthyr Tydfil","postcode":"CF47 8AU","telephone":"01685 373311","website":"http://www.4surewales.co.uk", photo: ''},{ ...}]

  def index
    category  = params[:category]
    tag       = params[:tag]
    query     = params[:query]
    page      = params[:page]
    since     = params[:since]

    @businesses = Business.order_by("name asc")
    @businesses = @businesses.where(:updated_at.gte => Time.parse(since)) if since.present?
    @businesses = @businesses.where(category: category) if category.present?
    @businesses = @businesses.where(:services => /#{tag}/) if tag.present?
    @businesses = @businesses.or(services: /#{query}/i).or(name: /#{query}/i) if query.present?
    @businesses = @businesses.page(page).per(PER_PAGE) if page.present?

    respond_with @businesses
  end

  ##
  # Returns the business for the given post id
  #
  # GET /api/v1/business/564c57c8663849b587000001
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/business/564c57c8663849b587000001
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   => {"name":"4 Sure Wales","category":"Services","contact":"Stephen Bew","address":"7 Glebeland Street ","town":"Merthyr Tydfil","postcode":"CF47 8AU","telephone":"01685 373311","website":"http://www.4surewales.co.uk","email":"steve@4surewales.co.uk","twitter":"@","facebook":false,"services":"insurance,general insurance,house insurance,car insurance,travel insurance,liability insurance,business insurance","profile":"","photo":"/uploads/business/photo/522e2ea69ef1ea5cdf000008/small_thumb_SAM_1422.JPG","coordinates":[-3.3790813,51.7465215],"zone":"Main BID","monday":"9am - 9am","tuesday":"9am - 9am","wednesday":"9am - 9am","thursday":"9am - 9am","friday":"9am - 9am","saturday":"9am - 9am","sunday":"Closed"}
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/business/not_existing_record
  #
  #   resp.status
  #   => 404
  #
  #   resp.body
  #   => {"message": "Resource not found"}
  #
  
  def show
    @business = Business.find(params[:id])
    respond_with @business
  end
end

app/controllers/api/v1/deals_controller.rb
class Api::V1::DealsController < Api::BaseController

  ##
  # Returns all approved and available deals
  #
  # GET /api/v1/deals
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/deals
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   [{"id":"52f618268eb4000495000001","title":"Valentines gift package for \u00a345","business":"Ann's Flowers ","end_date":"2014-02-14"}, {...}]

  def index
    since     = params[:since]

    @deals = Deal.approved.available.newest
    @deals = @deals.where(:updated_at.gte => Time.parse(since)) if since.present?
    respond_with @deals
  end

  ##
  # Returns the deal for the given deal id
  #
  # GET /api/v1/deals/564c57c8663849b587000001
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/deals/564c57c8663849b587000001
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   => {"title":"Valentines gift package for \u00a345","description":"","business":"Ann's Flowers ","start_date":"2014-02-08",
  #       "end_date":"2014-02-14", "terms":"term text,
  #       "image":"/uploads/deal/image/52f618268eb4000495000001/thumb_freedom.jpg"}
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/deals/not_existing_record
  #
  #   resp.status
  #   => 404
  #
  #   resp.body
  #   => {"message": "Resource not found"}
  #

  def show
    @deal = Deal.find(params[:id])
    respond_with @deal
  end
end

app/controllers/api/v1/deleted_records_controller.rb
class Api::V1::DeletedRecordsController < Api::BaseController

  def index
    since     = params[:since]

    @deleted_records = DeletedRecord.order_by(created_at: :desc)
    @deleted_records = @deleted_records.where(:created_at.gt => Time.parse(since)) if since.present?

    respond_with @deleted_records
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::BaseController

  ##
  # Returns all sheduled events.
  #
  # GET /api/v1/events
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/events
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   [{"id":"54f730e2f961bf93e9000001","name":"Global Village Festival","location_name":"Penderyn Square","image":"/uploads/event/image/54f730e2f961bf93e9000001/landscape_small_thumb_Global_Village.JPG","duration":21600},{...}]
  def index
    since     = params[:since]
    @events = Event.where(:next_occurrence.gte => Time.now).asc(:next_occurrence)
    @events = @events.where(:updated_at.gte => Time.parse(since)) if since.present?
    respond_with @events
  end

  ##
  # Returns the event for the given event id
  #
  # GET /api/v1/events/564c57c8663849b587000001
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/events/564c57c8663849b587000001
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   => {"name":"Global Village Festival","description": "description", "location_name":"Penderyn Square",
  #       "location_address":"Merthyr Tydfil Town Centre","coordinates":[-3.381646,51.74872999999999],
  #       "starts":"2015-05-16T11:00:00+00:00","ends":"2015-05-16T17:00:00+00:00",
  #       "next_occurrence":"2015-05-16T11:00:00+00:00","duration":21600,
  #       "small_image":"/uploads/event/image/54f730e2f961bf93e9000001/landscape_small_thumb_Global_Village.JPG",
  #       "big_image":"/uploads/event/image/54f730e2f961bf93e9000001/landscape_big_thumb_Global_Village.JPG"}
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/events/not_existing_record
  #
  #   resp.status
  #   => 404
  #
  #   resp.body
  #   => {"message": "Resource not found"}
  #
  def show
    @event = Event.find(params[:id])
    respond_with @event
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::BaseController

  ##
  # Returns all posts within the last 6 months
  #
  # GET /api/v1/posts
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/posts
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   [{"id":"564c57c8663849b587000001","published_at":"2015-11-18T10:49:44+00:00","title":"Merthyr Winter Market & Skating Rink Returns","category":"News","image":"/uploads/post/image/564c57c8663849b587000001/landscape_big_thumb_PO_061214_Merthyr_On_Ice_39.jpg"}, {...} ]
  
  def index
    @posts = Post.published.where(:published_at.gte => 6.months.ago).order_by(published_at: :desc)
    respond_with @posts
  end

  ##
  # Returns the post for the given post id
  #
  # GET /api/v1/posts/564c57c8663849b587000001
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/posts/564c57c8663849b587000001
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   => {"published_at":"2015-11-18T10:49:44+00:00","title":"Merthyr Winter Market & Skating Rink Returns", 
  #       "body": "text", ,"category":"News",
  #       "image":"/uploads/post/image/564c57c8663849b587000001/landscape_big_thumb_PO_061214_Merthyr_On_Ice_39.jpg"}
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/posts/not_existing_record
  #
  #   resp.status
  #   => 404
  #
  #   resp.body
  #   => {"message": "Resource not found"}
  #

  def show
    @post = Post.published.find(params[:id])
    respond_with @post
  end
end

app/helpers/api/v1/businesses_helper.rb
module Api::V1::BusinessesHelper
end

app/helpers/api/v1/deals_helper.rb
module Api::V1::DealsHelper
end

app/helpers/api/v1/deleted_records_helper.rb
module Api::V1::DeletedRecordsHelper
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/views/pages/v1/blog.html.erb
<div class="dow">
  <div class="col-lg-8 content">
      <div class="bread_crumbs">
        <%= link_to 'Home', front_path -%> > News
      </div>
      <h1 class="red">News</h1>
  </div>
  <div class="col-lg-4">
  </div>
</div>

<div class="col-lg-8 content">
  <div class="blog">
    <ul class="posts_list">
      <%- @posts.each do |p| -%>
        <li>
          <div class="post_header">
            <div class="post_date">
              <span class="day"><%= p.published_at.strftime("%d") -%></span>
              <span class="month"><%= p.published_at.strftime("%B") -%></span>
            </div>
            <h4 class="red"> <%= link_to p.title, blog_post_path(p) -%> </h4>
            <div class="entry_meta">
              <span class="post_category">
                <a href="#"><%= p.category -%></a>
              </span>
              <!--
              |
              <span class="post_author">
                Author: Lyn Williams
              </span>-->
            </div>
          </div>
          <%- if p.image.present? -%>
            <div class="post_thumbnail">
              <%= link_to blog_post_path(p), class: 'thumbnail' do -%>
                <%= image_tag p.image_url("#{p.image_mode}_big_thumb".to_sym) -%>
              <%- end -%>
            </div>
          <%- end -%>

          <%- truncated_100 = strip_tags(p.body)[/(\s*\S+){,100}/] -%>

          <%- if truncated_100.length < p.body.length -%>
            <%= raw truncated_100 -%>
            <%= link_to '...more', blog_post_path(p), class: 'more_post' -%>
          <%- else -%>
            <%= raw p.body -%>
          <%- end -%>
        </li>
      <%- end -%>
    </ul>

    <ul class="pagination">
      <%= paginate @posts -%>
     </ul>
  </div>
</div>

<div class="col-lg-4 sidebar">
  <div class="widget">
    <!--<h3 class="red">Categories</h3>-->
    <!--<div class="widget_categories">-->
      <!--< %- Post::CATEGORIES.sample(6).each do |c| -%>-->
        <!--< %= link_to c, '#', class: 'btn btn-s btn-black' -%>-->
      <!--< %- end -%>-->
    <!--</div>-->
  </div>
  <div class="widget">
    <%= render partial: 'shared/sidebar_socials' -%>
  </div>
</div>

app/views/pages/v1/edit.html.erb
<div class="content">
  <h4 class="section-subtitle"><b>Edit</b> page</h4>
  <!-- content HEADER -->
  <!-- ========================================================= -->
  <div class="content-header">
   <!-- leftside content header -->
    <div class="leftside-content-header">
     <ul class="breadcrumbs">
       <li><i class="fa fa-columns" aria-hidden="true"></i><a href="#">Page</a> <a href="#">Edit</a></li>
     </ul>
    </div>
  </div>

  <%= render 'form' %>

  <%= link_to 'Show', @page %> |
  <%= link_to 'Back', pages_path %>
</div>

app/views/pages/v1/new_subscriber.html.erb
<%= content_for :bread_crumbs do -%>
  <div class="dow">
    <div class="col-lg-8 col-md-8 content">
      <div class="bread_crumbs">
        <%= link_to 'Home', front_path -%> > New Subscriber
      </div>
      <h1 class="red">Sign Up/ Register Your Loyalty Card</h1>
      <p style="color: grey;">Enter your details below to order and register for the We Love Merthyr Loyalty Card. You'll also get the latest offers by email or sms.</p>
      <%= simple_form_for @subscriber, url: create_subscriber_path,  html: { class: 'form-horizontal'}, defaults: { input_html: { class: 'form-control' }} do |f| %>
        <div class="row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="first_name" class="col-lg-4 control-label">First Name<span class="require">*</span></label>
              <div class="col-lg-8">
                <div>
                  <%= f.input :first_name, label: false%>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="form-group">
              <label for="last_name" class="col-lg-4 control-label">Last Name<span class="require">*</span></label>
              <div class="col-lg-8">
                <div class="">
                  <%= f.input :last_name, label: false%>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="email" class="col-lg-4 control-label">Email<span class="require">*</span></label>
              <div class="col-lg-8">
                <div class="">
                  <%= f.input :email, label: false-%>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="form-group">
              <label for="mobile" class="col-lg-4 control-label">Mobile</label>
              <div class="col-lg-8">
                <div class="">
                  <%= f.input :mobile, label: false%>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="postcode" class="col-lg-4 control-label">Postcode<span class="require">*</span></label>
              <div class="col-lg-8">
                <div class="">
                  <%= f.input :postcode, label: false%>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 content">
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="form-group">
              <label for="address" class="col-lg-2 control-label ">Address<span class="require">*</span></label>
              <div class="col-lg-9">
                <%= f.text_area :address, label: false, style: "height:154px; width:102%;"%>
              </div>
            </div>
          </div>
        </div>        
        <div class="row">
          <div class="col-lg-12">
            <div class="form-group">
              <%= f.radio_button :order_card, 'true', :checked => true, style: "margin-left:15%;width:9%" %>Do you wish to order a loyalty card?
              <br>
              <%= f.radio_button :order_card, 'false', style: "margin-left:15%;width:9%"%>Are you registering your existing loyalty card?
              <br>
              <br>
              <input type="checkbox" id="privacypolicy" style="margin-left:15%;width:9%;">By submitting your details to us you agree with our <%= link_to 'privacy policy', public_privacy_policy_path -%>.
            </div>
          </div>
        </div>
        <div class="row">          
          <div class="col-lg-12 content">
            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-9">
                <%= f.button :submit, value: "Submit", class: 'btn-default', :id => "newsubscribe"%>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br>
    <div class="col-lg-4 col-md-4">
      <div style="background-color: #E84530;padding: 1em;">       
        <h1 style="color: whitesmoke;">Do you have a loyalty card?</h1>
        <hr style="border-color: white;">
        <p style="font-size: 23px;font-weight: 700;color: whitesmoke;">You can order or register your loyalty card by clicking on the link below:</p>
        <a href="<%= public_new_subscriber_path -%>" class="btn-default btn-lg btn-block" style="text-align: center;color: #f94623;font-size: 23px;">Sign Up/ Register</a>
      </div>     
    </div>
  </div>
<%- end -%>


<script type="text/javascript">
  $(document).ready(function() {
   $('#newsubscribe').prop('disabled', true);
   $('input[id="privacypolicy"]').click(function () {
      if ($(this).prop('checked')) {
        $('#newsubscribe').prop('disabled', false);
      }
      else{
        $('#newsubscribe').prop('disabled', true);
      }
    });
  });
</script>

app/views/pages/v1/static_page.html.erb
<%= raw @page.body -%>

app/views/pages/v1/voucher.html.erb
<%= content_for :bread_crumbs do -%>
  <div class="dow margin_bottom_20">
    <div class="col-lg-8 content">
      <div class="bread_crumbs">
        <%= link_to 'Home', front_path -%> >
        <%= link_to 'Vouchers', public_vouchers_path -%> >
        <%= @deal.title -%>
      </div>
      <h1 class="red title_post"><%= @deal.title -%></h1>
      <div class="post_entry_meta">
        <div class="category underline">
          At <a href="<%= public_business_path(@deal.business) -%>"><%= @deal.business_name -%></a>, <%= @deal.business.full_address -%>
          <br />
          <div>
            Expiry date:
            <a href="#"><%= @deal.end_date.strftime("%B #{@deal.end_date.day.ordinalize}, %Y") -%></a>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
    </div>
    <div class="clearfix"></div>
  </div>
<%- end -%>

<div class="col-lg-8 content">
  <div class="blog">
        <div class="row">
          <div class="col-xs-12 col-sm-8 col-md-8 col-lg-6 ">
            <%=raw @deal.description -%>

            <h2 class="red">Terms and Conditions</h2>

            <%= @deal.terms -%>

            <br />
            <br />

            <!-- <div class="a_center">
              <a href="#subscribe_1" class="btn btn-lg btn-success margin_top_10 fancybox">Claim Voucher</a>
              <a href="#subscribe_2" class="fancybox hide"></a>
            </div> -->
          </div >

          <div class="col-xs-12 col-sm-4 col-md-4 col-lg-6 a_center">
            <%- if @deal.image_url(:thumb).present? -%>
              <div class="thumbnail">
                <%= image_tag @deal.image_url(:thumb) -%>
              </div>
            <%- else -%>
              <div class="thumbnail">
                <div style="width:358px;height:273px;background-color:#ccc"></div>
              </div>
            <%- end -%>
          </div>
        </div>
        <div class="social_shared">
          <span class='st_twitter_vcount' displayText='Tweet'></span>
          <span class='st_facebook_vcount' displayText='Facebook'></span>
          <span class='st_googleplus_vcount' displayText='Google +'></span>
          <span class='st_email_vcount' displayText='Email'></span>
        </div>
  </div>
</div>

<div class="col-lg-4 sidebar">
  <div class="widget">
    <h2 class="red">Recent Vouchers</h2>
    <div class="widget_recent_posts widget_recent_vouchers">
      <%- Deal.latest(5).reject { |d| d.id == @deal.id }.each do |d| -%>
        <div class="recent_post">
          <a href="#" class="title"> <%= d.title -%> </a>
          <div class="recent_posts_entry_meta ">
              > Expires: <a href="#"><%= d.end_date.strftime("%B #{d.end_date.day.ordinalize}, %Y") -%></a>
          </div>
        </div>
      <%- end -%>
    </div>
  </div>
  <div class="widget">
    <%= render partial: 'shared/sidebar_socials' -%>
  </div>
</div>

<div id="subscribe_1" style="display:none">
  <div class='col-lg-12'>
    <div class='col-lg-12' id="manual">
      <%= render partial: 'subscribers/manual', locals: { object: Subscriber.new(deal_id: @deal.id) } -%>
    </div>
    <hr/>
    <div class='col-lg-12'>
      <div class="control-group form-group">
        <div class="control-label col-lg-2">&nbsp;</div>
          <%= link_to '#', id: 'subscribe_with_facebook', class: 'btn btn-s btn-dark_blue' do -%>
            <span class="glyphicon icon-facebook-sign"></span>
            Claim with Facebook
          <%- end -%>
      </div>
    </div>
  </div>
</div>

<div id="subscribe_2" style="display:none">
  <%= link_to 'Print/Display voucher', public_voucher_path(@deal, format: 'pdf'), target: 'blank', class: 'btn btn-primary' -%>
</div>

<%- if params[:step].to_i == 2 -%>
  <script type="text/javascript">
    $(document).ready(function() {
      $("a[href='#subscribe_2']").click();
    });
  </script>
<%- end -%>

app/views/pages/v1/vouchers.html.erb
<%= content_for :bread_crumbs do -%>
  <div class="dow">
    <div class="col-lg-8 content">
      <div class="bread_crumbs">
        <%= link_to 'Home', front_path -%> > Deals
      </div>
      <h1 class="red">Deals available with your Loyalty Card</h1>
      <div class="vouchers">
        <ul class="vouchers_list">
          <%- @deals.each do |deal| -%>
            <li>
              <div>
                <div class="col-lg-9">
                  <h4><%= link_to deal.title, public_voucher_path(deal) -%></h4>
                  <p>
                    <%= link_to deal.business.name, public_business_path(deal.business), class: 'blue under' -%>,
                    <%= deal.business.full_address -%>
                  </p>
                  <p class="voucher_expires">Voucher expires: <%= deal.end_date.try(:strftime, "#{deal.end_date.try(:day).try(:ordinalize)} %B %Y") -%></p>
                  <div class="share_via">
                    <p>Share via:</p>
                    <div>
                      <!-- AddThis Button BEGIN -->
                      <div class="addthis_toolbox addthis_default_style ">
                        <span style="float:left"> <fb:like href="<%= public_voucher_url(deal) -%>" layout="button_count" action="like" show_faces="false"></fb:like></span>
                        <!--<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>-->
                        <a class="addthis_button_tweet" style="width:80px"></a>
                        <a class="addthis_button_pinterest_pinit" style="width:50px" pi:pinit:layout="horizontal"></a>
                        <a class="addthis_counter addthis_pill_style"></a>
                      </div>
                      <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
                      <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-526e92c31dafd4cc"></script>
                      <!-- AddThis Button END -->
                      <div class="clearfix"></div>
                    </div>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="col-lg-3 claim_voucher">
                  
                </div>
              </div>
            </li>
          <%- end -%>
        </ul>
        <ul class="pagination">
          <%= paginate @deals -%>
        </ul>
      </div>
    </div>
    <br>
    <div class="col-lg-4 col-md-4">
      <div style="background-color: #E84530;padding: 1em;">       
        <h1 style="color: whitesmoke;">Do you have a loyalty card?</h1>
        <hr style="border-color: white;">
        <p style="font-size: 23px;font-weight: 700;color: whitesmoke;">You can order or register your loyalty card by clicking on the link below:</p>
        <a href="<%= public_new_subscriber_path -%>" class="btn-default btn-lg btn-block" style="text-align: center;color: #f94623;font-size: 23px;">Sign Up/ Register</a>
      </div>     
    </div>
  </div>
<%- end -%>